version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: clinica_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: clinica_backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: clinica_frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000/api
    depends_on:
      - backend

volumes:
  mongo_data: